SELECT CURRENT_ROLE();


CREATE DATABASE IF NOT EXISTS INSURANCE_CLAIMS_DB;

SELECT CURRENT_DATABASE();


CREATE SCHEMA IF NOT EXISTS CLAIMS;

SELECT CURRENT_SCHEMA();


CREATE WAREHOUSE IF NOT EXISTS INSURANCE_CLAIMS_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

SELECT CURRENT_WAREHOUSE();


SELECT 
    CURRENT_ROLE() AS CURRENT_ROLE,
    CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
    CURRENT_DATABASE() AS CURRENT_DATABASE,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA;