USE DATABASE INSURANCE_CLAIMS_DB;
USE SCHEMA CLAIMS;
USE WAREHOUSE INSURANCE_CLAIMS_WH;



---------------------------------------------------------------------------------------------------------------------
-------------------------------------------------Main Analytical View---------------------------------------------
---------------------------------------------------------------------------------------------------------------------


-- Create CLAIMS_ANALYTICS_VW

CREATE OR REPLACE VIEW CLAIMS_ANALYTICS_VW AS
SELECT
    TRANSACTION_ID,
    CUSTOMER_ID,
    POLICY_NUMBER,

    TXN_DATE_TIME,
    POLICY_EFF_DT,
    LOSS_DT,
    REPORT_DT,

    INSURANCE_TYPE,

    PREMIUM_AMOUNT,
    CLAIM_AMOUNT,
    CLAIM_TO_PREMIUM_RATIO,

    CITY,
    STATE,

    MARITAL_STATUS,
    AGE,
    AGE_GROUP,
    TENURE,
    TENURE_GROUP,
    EMPLOYMENT_STATUS,
    NO_OF_FAMILY_MEMBERS,

    RISK_SEGMENTATION,
    HOUSE_TYPE,
    SOCIAL_CLASS,
    CUSTOMER_EDUCATION_LEVEL,

    CLAIM_STATUS,
    INCIDENT_SEVERITY,
    AUTHORITY_CONTACTED,
    ANY_INJURY,
    POLICE_REPORT_AVAILABLE,

    INCIDENT_STATE,
    INCIDENT_CITY,
    INCIDENT_HOUR_OF_THE_DAY,

    AGENT_ID,
    VENDOR_ID,

    REPORTING_DELAY_DAYS,
    REPORTING_CATEGORY,

    CLAIM_VALUE_CATEGORY,

    LOSS_YEAR,
    LOSS_MONTH,
    LOSS_MONTH_NAME

FROM INSURANCE_ANALYTICS;


-- Validate Main View

SELECT 
    COUNT(*) AS TOTAL_ROWS
FROM CLAIMS_ANALYTICS_VW;


SELECT TOP 10
    *
FROM CLAIMS_ANALYTICS_VW;


--------------------------------------------------Claims Summary View-------------------------------------------------

CREATE OR REPLACE VIEW CLAIMS_SUMMARY_VW AS
SELECT
    COUNT(*) AS TOTAL_CLAIMS,
    ROUND(SUM(CLAIM_AMOUNT), 2) AS TOTAL_CLAIM_AMOUNT,
    ROUND(AVG(CLAIM_AMOUNT), 2) AS AVG_CLAIM_AMOUNT,
    ROUND(MEDIAN(CLAIM_AMOUNT), 2) AS MEDIAN_CLAIM_AMOUNT,
    ROUND(SUM(PREMIUM_AMOUNT), 2) AS TOTAL_PREMIUM,
    ROUND(AVG(PREMIUM_AMOUNT), 2) AS AVG_PREMIUM,
    ROUND(AVG(CLAIM_TO_PREMIUM_RATIO), 2) AS AVG_CLAIM_TO_PREMIUM_RATIO,
    ROUND(AVG(REPORTING_DELAY_DAYS), 2) AS AVG_REPORTING_DELAY_DAYS,
    COUNT_IF(REPORTING_DELAY_DAYS = 0) AS SAME_DAY_CLAIMS,
    ROUND(COUNT_IF(REPORTING_DELAY_DAYS = 0) * 100.0 / COUNT(*), 2) AS SAME_DAY_REPORTING_PERCENTAGE,
    COUNT_IF(CLAIM_AMOUNT >= 50000) AS HIGH_VALUE_CLAIMS,
    ROUND(COUNT_IF(CLAIM_AMOUNT >= 50000) * 100.0 / COUNT(*),  2) AS HIGH_VALUE_CLAIM_PERCENTAGE
FROM INSURANCE_ANALYTICS;



SELECT 
    *
FROM CLAIMS_SUMMARY_VW;



----------------------------------------------------------------------------------------------------------------------------------
-- Insurance Type View


CREATE OR REPLACE VIEW INSURANCE_TYPE_VW AS
SELECT
    INSURANCE_TYPE,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(SUM(CLAIM_AMOUNT), 2)  AS TOTAL_CLAIM_AMOUNT,
    ROUND(AVG(CLAIM_AMOUNT), 2)  AS AVG_CLAIM_AMOUNT,
    ROUND(AVG(PREMIUM_AMOUNT), 2)  AS AVG_PREMIUM,
    ROUND(AVG(CLAIM_TO_PREMIUM_RATIO), 2)  AS AVG_CLAIM_TO_PREMIUM_RATIO,
    ROUND(AVG(REPORTING_DELAY_DAYS), 2)  AS AVG_REPORTING_DELAY_DAYS,
    ROUND(COUNT_IF(REPORTING_DELAY_DAYS = 0) * 100.0 / COUNT(*),  2) AS SAME_DAY_REPORTING_PERCENTAGE
FROM INSURANCE_ANALYTICS
GROUP BY INSURANCE_TYPE;

-------------------------------------------Check:-------------

SELECT *
FROM INSURANCE_TYPE_VW
ORDER BY TOTAL_CLAIM_AMOUNT DESC;

----------------------------------------------------------- Risk Segment View--------------------------------------------------------

CREATE OR REPLACE VIEW RISK_SEGMENT_VW AS
SELECT
    RISK_SEGMENTATION,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(SUM(CLAIM_AMOUNT), 2) AS TOTAL_CLAIM_AMOUNT,
    ROUND(AVG(CLAIM_AMOUNT), 2) AS AVG_CLAIM_AMOUNT,
    ROUND(AVG(PREMIUM_AMOUNT), 2) AS AVG_PREMIUM,
    ROUND(AVG(CLAIM_TO_PREMIUM_RATIO), 2) AS AVG_CLAIM_TO_PREMIUM_RATIO,
    ROUND(AVG(REPORTING_DELAY_DAYS), 2) AS AVG_REPORTING_DELAY_DAYS,
    COUNT_IF(CLAIM_AMOUNT >= 50000) AS HIGH_VALUE_CLAIMS
FROM INSURANCE_ANALYTICS
GROUP BY RISK_SEGMENTATION;

--------------------------- Check--------------------------

SELECT 
    *
FROM RISK_SEGMENT_VW
ORDER BY TOTAL_CLAIM_AMOUNT DESC;


-----------------------------------------------Incident Severity View----------------------------------------------------------

CREATE OR REPLACE VIEW INCIDENT_SEVERITY_VW AS
SELECT
    INCIDENT_SEVERITY,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(SUM(CLAIM_AMOUNT), 2) AS TOTAL_CLAIM_AMOUNT,
    ROUND(AVG(CLAIM_AMOUNT), 2) AS AVG_CLAIM_AMOUNT,
    ROUND(AVG(REPORTING_DELAY_DAYS), 2) AS AVG_REPORTING_DELAY_DAYS,
    COUNT_IF(ANY_INJURY = 1) AS INJURY_CLAIM_COUNT
FROM INSURANCE_ANALYTICS
GROUP BY INCIDENT_SEVERITY;

--------------------------- Check--------------------------
SELECT 
    *
FROM INCIDENT_SEVERITY_VW
ORDER BY TOTAL_CLAIM_AMOUNT DESC;


-------------------------------------------------------Agent Performance View----------------------------------------------------------


CREATE OR REPLACE VIEW AGENT_PERFORMANCE_VW AS
SELECT
    I.AGENT_ID,
    E.AGENT_NAME,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(SUM(I.CLAIM_AMOUNT), 2)  AS TOTAL_CLAIM_AMOUNT,
    ROUND(AVG(I.CLAIM_AMOUNT), 2)  AS AVG_CLAIM_AMOUNT,
    ROUND(AVG(I.REPORTING_DELAY_DAYS), 2)  AS AVG_REPORTING_DELAY_DAYS,
    COUNT_IF(I.CLAIM_AMOUNT >= 50000) AS HIGH_VALUE_CLAIMS,
    ROUND(COUNT_IF(I.REPORTING_DELAY_DAYS = 0) * 100.0 / COUNT(*), 2) AS SAME_DAY_REPORTING_PERCENTAGE
FROM INSURANCE_ANALYTICS I
LEFT JOIN EMPLOYEE_CLEANED E
    ON I.AGENT_ID = E.AGENT_ID
GROUP BY
    I.AGENT_ID,
    E.AGENT_NAME;

--------------------------- Check--------------------------
SELECT  TOP 10
    *
FROM AGENT_PERFORMANCE_VW
ORDER BY TOTAL_CLAIM_AMOUNT DESC;


---------------------------------------------------------Vendor Performance View----------------------------------------------------------


CREATE OR REPLACE VIEW VENDOR_PERFORMANCE_VW AS
SELECT
    I.VENDOR_ID,
    V.VENDOR_NAME,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(SUM(I.CLAIM_AMOUNT), 2) AS TOTAL_CLAIM_AMOUNT,
    ROUND(AVG(I.CLAIM_AMOUNT), 2) AS AVG_CLAIM_AMOUNT,
    ROUND(AVG(I.REPORTING_DELAY_DAYS), 2) AS AVG_REPORTING_DELAY_DAYS,
    COUNT_IF(I.CLAIM_AMOUNT >= 50000) AS HIGH_VALUE_CLAIMS
FROM INSURANCE_ANALYTICS I
LEFT JOIN VENDOR_CLEANED V
    ON I.VENDOR_ID = V.VENDOR_ID
WHERE I.VENDOR_ID IS NOT NULL
GROUP BY
    I.VENDOR_ID,
    V.VENDOR_NAME;

--------------------------- Check--------------------------
SELECT TOP 10
    *
FROM VENDOR_PERFORMANCE_VW
ORDER BY TOTAL_CLAIM_AMOUNT DESC;




----------------------------------------------- Monthly Claims Trend View ----------------------------------------------------


CREATE OR REPLACE VIEW MONTHLY_CLAIMS_TREND_VW AS
SELECT
    LOSS_YEAR,
    LOSS_MONTH,
    LOSS_MONTH_NAME,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(SUM(CLAIM_AMOUNT), 2) AS TOTAL_CLAIM_AMOUNT,
    ROUND(AVG(CLAIM_AMOUNT), 2) AS AVG_CLAIM_AMOUNT,
    ROUND(AVG(REPORTING_DELAY_DAYS), 2)    AS AVG_REPORTING_DELAY_DAYS,
    SUM(IFF(CLAIM_AMOUNT >= 50000 , 1, 0))  AS HIGH_VALUE_CLAIMS
FROM INSURANCE_ANALYTICS
GROUP BY
    LOSS_YEAR,
    LOSS_MONTH,
    LOSS_MONTH_NAME;

-- Check:

SELECT 
    *
FROM MONTHLY_CLAIMS_TREND_VW
ORDER BY LOSS_YEAR, LOSS_MONTH;

    
------------------------------------------------- State Analysis View-------------------------------------------------------

CREATE OR REPLACE VIEW STATE_CLAIMS_VW AS
SELECT
    STATE,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(SUM(CLAIM_AMOUNT), 2) AS TOTAL_CLAIM_AMOUNT,
    ROUND(AVG(CLAIM_AMOUNT), 2) AS AVG_CLAIM_AMOUNT,
    ROUND(AVG(REPORTING_DELAY_DAYS), 2) AS AVG_REPORTING_DELAY_DAYS,
    COUNT_IF(CLAIM_AMOUNT >= 50000) AS HIGH_VALUE_CLAIMS
FROM INSURANCE_ANALYTICS
GROUP BY STATE;

-- Check:

SELECT 
    *
FROM STATE_CLAIMS_VW
ORDER BY TOTAL_CLAIM_AMOUNT DESC;


-----------------------------------------------Investigation Priority View------------------------------------------------------

CREATE OR REPLACE VIEW CLAIM_INVESTIGATION_PRIORITY_VW AS
SELECT
    TRANSACTION_ID,
    POLICY_NUMBER,

    INSURANCE_TYPE,
    STATE,

    RISK_SEGMENTATION,
    INCIDENT_SEVERITY,

    CLAIM_AMOUNT,
    PREMIUM_AMOUNT,
    CLAIM_TO_PREMIUM_RATIO,

    REPORTING_DELAY_DAYS,

    CASE
        WHEN RISK_SEGMENTATION = 'High'
            THEN 1
        ELSE 0
    END AS HIGH_RISK_FLAG,

    CASE
        WHEN CLAIM_AMOUNT >= 50000
            THEN 1
        ELSE 0
    END AS HIGH_VALUE_FLAG,

    CASE
        WHEN CLAIM_TO_PREMIUM_RATIO >= 500
            THEN 1
        ELSE 0
    END AS HIGH_RATIO_FLAG,

    CASE
        WHEN REPORTING_DELAY_DAYS >= 3
            THEN 1
        ELSE 0
    END AS DELAYED_REPORT_FLAG,

    (
        CASE
            WHEN RISK_SEGMENTATION = 'High' THEN 1
            ELSE 0
        END
        +
        CASE
            WHEN CLAIM_AMOUNT >= 50000 THEN 1
            ELSE 0
        END
        +
        CASE
            WHEN CLAIM_TO_PREMIUM_RATIO >= 500 THEN 1
            ELSE 0
        END
        +
        CASE
            WHEN REPORTING_DELAY_DAYS >= 3 THEN 1
            ELSE 0
        END
    ) AS INVESTIGATION_PRIORITY_SCORE

FROM INSURANCE_ANALYTICS;

--Check

SELECT TOP 10
    *
FROM CLAIM_INVESTIGATION_PRIORITY_VW
ORDER BY
    INVESTIGATION_PRIORITY_SCORE DESC,
    CLAIM_AMOUNT DESC;




------------------------------------------------Final View Validation------------------------------------------------------

SELECT
    'CLAIMS_ANALYTICS_VW' AS VIEW_NAME,
    COUNT(*) AS ROW_COUNT
FROM CLAIMS_ANALYTICS_VW

UNION ALL

SELECT
    'INSURANCE_TYPE_VW',
    COUNT(*)
FROM INSURANCE_TYPE_VW

UNION ALL

SELECT
    'RISK_SEGMENT_VW',
    COUNT(*)
FROM RISK_SEGMENT_VW

UNION ALL

SELECT
    'INCIDENT_SEVERITY_VW',
    COUNT(*)
FROM INCIDENT_SEVERITY_VW

UNION ALL

SELECT
    'AGENT_PERFORMANCE_VW',
    COUNT(*)
FROM AGENT_PERFORMANCE_VW

UNION ALL

SELECT
    'VENDOR_PERFORMANCE_VW',
    COUNT(*)
FROM VENDOR_PERFORMANCE_VW

UNION ALL

SELECT
    'MONTHLY_CLAIMS_TREND_VW',
    COUNT(*)
FROM MONTHLY_CLAIMS_TREND_VW

UNION ALL

SELECT
    'STATE_CLAIMS_VW',
    COUNT(*)
FROM STATE_CLAIMS_VW

UNION ALL

SELECT
    'CLAIM_INVESTIGATION_PRIORITY_VW',
    COUNT(*)
FROM CLAIM_INVESTIGATION_PRIORITY_VW;
